from datetime import datetime, timedelta
from typing import List, Dict


def d(days: int) -> str:
    """Returns a date string N days from now"""
    return (datetime.now() + timedelta(days=days)).strftime("%Y-%m-%d")


def to_firestore(db, scholarships: List[Dict]) -> int:
    count = 0
    col = db.collection("scholarships")
    for s in scholarships:
        try:
            doc_id = s.get("source_id", "").replace(" ", "_").lower()
            if not doc_id:
                continue
            col.document(doc_id).set({
                **s,
                "is_active": True,
                "last_scraped": datetime.utcnow().isoformat()
            })
            count += 1
        except Exception as e:
            print(f"Error saving {s.get('name')}: {e}")
    return count


# ── 1. CENTRAL GOVERNMENT - NSP ─────────────────────────

def get_central_govt() -> List[Dict]:
    return [
        {
            "source_id": "nsp_central_sector_css",
            "name": "Central Sector Scheme of Scholarships (CSSS)",
            "source": "NSP - Ministry of Education",
            "amount": 20000,
            "description": "For meritorious students from low-income families pursuing UG/PG at colleges/universities. 82,000 scholarships per year, 50% reserved for girls.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 450000, "minPercentage": 80, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(120), "applyLink": "https://scholarships.gov.in",
            "documents": ["Class XII marksheet (80%+)", "Income certificate", "Aadhaar", "Bank passbook", "Admission proof"],
            "tags": ["central", "merit", "nsp", "all categories"],
        },
        {
            "source_id": "nsp_nmms",
            "name": "National Means-cum-Merit Scholarship (NMMS)",
            "source": "NSP - Ministry of Education",
            "amount": 12000,
            "description": "For Class 9-12 students from low-income families to prevent dropout. 1 lakh scholarships annually.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 350000, "minPercentage": 55, "educationLevels": ["9th", "10th", "11th", "12th"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarships.gov.in",
            "documents": ["Class 8 marksheet (55%+)", "Income certificate", "Aadhaar", "School certificate"],
            "tags": ["central", "school", "nmms", "nsp"],
        },
        {
            "source_id": "nsp_postmatric_sc",
            "name": "Post Matric Scholarship for SC Students",
            "source": "NSP - Ministry of Social Justice",
            "amount": 15000,
            "description": "Financial assistance to SC students studying at post-matriculation stage to complete their education.",
            "eligibility": {"categories": ["sc"], "states": ["all"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg", "phd", "diploma"], "gender": "all"},
            "deadline": d(120), "applyLink": "https://scholarships.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar", "Bank passbook"],
            "tags": ["sc", "postmatric", "central", "nsp"],
        },
        {
            "source_id": "nsp_prematric_sc",
            "name": "Pre Matric Scholarship for SC Students (Class 9-10)",
            "source": "NSP - Ministry of Social Justice",
            "amount": 4000,
            "description": "For SC students in Class 9 and 10 to reduce dropout and encourage continuation of education.",
            "eligibility": {"categories": ["sc"], "states": ["all"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["9th", "10th"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://scholarships.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Aadhaar", "School certificate"],
            "tags": ["sc", "prematric", "central", "nsp", "school"],
        },
        {
            "source_id": "nsp_postmatric_st",
            "name": "Post Matric Scholarship for ST Students",
            "source": "NSP - Ministry of Tribal Affairs",
            "amount": 15000,
            "description": "Scholarship for ST students pursuing post-matriculation courses to complete education without financial hardship.",
            "eligibility": {"categories": ["st"], "states": ["all"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg", "phd", "diploma"], "gender": "all"},
            "deadline": d(120), "applyLink": "https://scholarships.gov.in",
            "documents": ["Tribal certificate", "Income certificate", "Marksheet", "Aadhaar", "Bank passbook"],
            "tags": ["st", "tribal", "postmatric", "central", "nsp"],
        },
        {
            "source_id": "nsp_prematric_st",
            "name": "Pre Matric Scholarship for ST Students (Class 9-10)",
            "source": "NSP - Ministry of Tribal Affairs",
            "amount": 4000,
            "description": "For ST students in Class 9 and 10 to prevent dropouts and promote tribal education.",
            "eligibility": {"categories": ["st"], "states": ["all"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["9th", "10th"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://scholarships.gov.in",
            "documents": ["Tribal certificate", "Income certificate", "Aadhaar", "School certificate"],
            "tags": ["st", "prematric", "central", "nsp", "school"],
        },
        {
            "source_id": "nsp_postmatric_obc",
            "name": "Post Matric Scholarship for OBC Students",
            "source": "NSP - Ministry of Social Justice",
            "amount": 12000,
            "description": "Scholarship for OBC students to pursue post-matriculation education and reduce dropout rates.",
            "eligibility": {"categories": ["obc"], "states": ["all"], "maxIncome": 100000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(115), "applyLink": "https://scholarships.gov.in",
            "documents": ["OBC certificate", "Income certificate", "Marksheet", "Aadhaar", "Bank passbook"],
            "tags": ["obc", "postmatric", "central", "nsp"],
        },
        {
            "source_id": "nsp_minority_prematric",
            "name": "Pre Matric Scholarship for Minority Students",
            "source": "NSP - Ministry of Minority Affairs",
            "amount": 10000,
            "description": "For minority students in Class 1-10 to reduce dropout and support basic education.",
            "eligibility": {"categories": ["minority"], "states": ["all"], "maxIncome": 100000, "minPercentage": 50, "educationLevels": ["9th", "10th"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://scholarships.gov.in",
            "documents": ["Minority certificate", "Income certificate", "Aadhaar", "School certificate"],
            "tags": ["minority", "prematric", "central", "nsp"],
        },
        {
            "source_id": "nsp_minority_postmatric",
            "name": "Post Matric Scholarship for Minority Students",
            "source": "NSP - Ministry of Minority Affairs",
            "amount": 12000,
            "description": "For Muslim, Christian, Sikh, Buddhist, Jain, Parsi students pursuing post-matriculation education.",
            "eligibility": {"categories": ["minority"], "states": ["all"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["11th", "12th", "ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://scholarships.gov.in",
            "documents": ["Minority certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["minority", "postmatric", "central", "nsp"],
        },
        {
            "source_id": "nsp_minority_merit_means",
            "name": "Merit-cum-Means Scholarship for Minority Students",
            "source": "NSP - Ministry of Minority Affairs",
            "amount": 30000,
            "description": "For minority students pursuing technical and professional courses. Covers course fee and maintenance.",
            "eligibility": {"categories": ["minority"], "states": ["all"], "maxIncome": 250000, "minPercentage": 50, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://scholarships.gov.in",
            "documents": ["Minority certificate", "Income certificate", "Marksheet", "Aadhaar", "Admission proof"],
            "tags": ["minority", "merit", "central", "nsp", "technical"],
        },
        {
            "source_id": "nsp_pragati_technical",
            "name": "Pragati Scholarship for Girl Students (Technical Degree)",
            "source": "NSP - AICTE",
            "amount": 50000,
            "description": "AICTE scholarship for girl students admitted to first year of AICTE approved degree/diploma programs.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 800000, "minPercentage": 0, "educationLevels": ["ug", "diploma"], "gender": "female"},
            "deadline": d(90), "applyLink": "https://scholarships.gov.in",
            "documents": ["Marksheet", "Income certificate", "Aadhaar", "AICTE institution letter", "Bank passbook"],
            "tags": ["girl", "technical", "aicte", "pragati", "nsp"],
        },
        {
            "source_id": "nsp_saksham_disability",
            "name": "Saksham Scholarship for Differently Abled Students",
            "source": "NSP - AICTE",
            "amount": 50000,
            "description": "AICTE scholarship for differently abled students (40%+ disability) pursuing technical education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 800000, "minPercentage": 0, "educationLevels": ["ug", "diploma"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://scholarships.gov.in",
            "documents": ["Disability certificate (40%+)", "Marksheet", "Income certificate", "Aadhaar"],
            "tags": ["disability", "pwd", "aicte", "saksham", "nsp"],
        },
        {
            "source_id": "nsp_ishan_uday_ne",
            "name": "Ishan Uday Scholarship for North East Region",
            "source": "NSP - UGC",
            "amount": 54000,
            "description": "For students from North East states pursuing general degree courses at UG level.",
            "eligibility": {"categories": ["all"], "states": ["Assam", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Tripura", "Arunachal Pradesh", "Sikkim"], "maxIncome": 450000, "minPercentage": 0, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://scholarships.gov.in",
            "documents": ["Domicile certificate", "Income certificate", "Class XII marksheet", "Aadhaar", "Admission proof"],
            "tags": ["north east", "ugc", "ishan uday", "nsp"],
        },
        {
            "source_id": "nsp_ugc_single_girl",
            "name": "UGC Single Girl Child Scholarship (PG Indira Gandhi)",
            "source": "NSP - UGC",
            "amount": 36200,
            "description": "For single girl child pursuing first postgraduate degree at a recognized university.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 0, "educationLevels": ["pg"], "gender": "female"},
            "deadline": d(130), "applyLink": "https://scholarships.gov.in",
            "documents": ["Single girl child affidavit", "UG marksheet", "Admission proof", "Aadhaar", "Bank passbook"],
            "tags": ["girl", "pg", "ugc", "single child", "nsp"],
        },
        {
            "source_id": "nsp_top_class_sc",
            "name": "Top Class Education Scheme for SC Students",
            "source": "NSP - Ministry of Social Justice",
            "amount": 200000,
            "description": "For SC students studying in top institutions (IITs, IIMs, AIIMS, NITs, etc.) covering full fees and maintenance.",
            "eligibility": {"categories": ["sc"], "states": ["all"], "maxIncome": 600000, "minPercentage": 0, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarships.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Admission letter from top institution", "Aadhaar"],
            "tags": ["sc", "top class", "iit", "iim", "central", "nsp"],
        },
        {
            "source_id": "nsp_pm_usp_jk",
            "name": "PM Special Scholarship Scheme for J&K and Ladakh",
            "source": "NSP - Ministry of Education",
            "amount": 100000,
            "description": "5000 scholarships for J&K and Ladakh students to study in institutions outside their UT.",
            "eligibility": {"categories": ["all"], "states": ["Jammu and Kashmir", "Ladakh"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://scholarships.gov.in",
            "documents": ["Domicile certificate (J&K/Ladakh)", "Class XII marksheet (60%+)", "Aadhaar", "Admission proof outside UT"],
            "tags": ["jk", "ladakh", "central", "nsp"],
        },
        {
            "source_id": "nsp_pw_disabilities",
            "name": "Scholarship for Top Class Education for Students with Disabilities",
            "source": "NSP - DEPwD",
            "amount": 200000,
            "description": "For students with disabilities (40%+) in top institutions covering full fees and maintenance allowance.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 600000, "minPercentage": 0, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://scholarships.gov.in",
            "documents": ["Disability certificate (40%+)", "Income certificate", "Admission letter", "Aadhaar"],
            "tags": ["disability", "pwd", "top class", "central", "nsp"],
        },
        {
            "source_id": "nsp_begum_hazrat_mahal",
            "name": "Begum Hazrat Mahal National Scholarship",
            "source": "NSP - Maulana Azad Education Foundation",
            "amount": 6000,
            "description": "For minority girl students in Class 9-12 with good academic record.",
            "eligibility": {"categories": ["minority"], "states": ["all"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["9th", "10th", "11th", "12th"], "gender": "female"},
            "deadline": d(115), "applyLink": "https://scholarships.gov.in",
            "documents": ["Minority certificate", "Income certificate", "Marksheet (50%+)", "Aadhaar", "School certificate"],
            "tags": ["minority", "girl", "school", "begum hazrat mahal", "nsp"],
        },
    ]


# ── 2. AICTE & UGC ──────────────────────────────────────

def get_aicte_ugc() -> List[Dict]:
    return [
        {
            "source_id": "aicte_swanath",
            "name": "AICTE Swanath Scholarship",
            "source": "AICTE",
            "amount": 50000,
            "description": "For orphans and wards of armed forces/paramilitary martyred in action, pursuing technical education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 800000, "minPercentage": 0, "educationLevels": ["ug", "diploma"], "gender": "all"},
            "deadline": d(88), "applyLink": "https://www.aicte-india.org/bureaus/pgms/swanath",
            "documents": ["Parent death/service certificate", "Aadhaar", "Marksheet", "Admission proof"],
            "tags": ["orphan", "armed forces", "aicte", "swanath"],
        },
        {
            "source_id": "aicte_pragati_diploma",
            "name": "AICTE Pragati Scholarship - Diploma",
            "source": "AICTE",
            "amount": 30000,
            "description": "For girl students admitted to first year of AICTE approved diploma programs.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 800000, "minPercentage": 0, "educationLevels": ["diploma"], "gender": "female"},
            "deadline": d(85), "applyLink": "https://www.aicte-india.org/bureaus/pgms/pragati",
            "documents": ["Aadhaar", "Income certificate", "Marksheet", "Admission letter"],
            "tags": ["girl", "diploma", "aicte", "pragati"],
        },
        {
            "source_id": "ugc_nspg",
            "name": "National Scholarship for PG Studies (NSPG)",
            "source": "UGC",
            "amount": 180000,
            "description": "UGC scholarship of ₹15,000/month for 10 months for meritorious PG students from economically weaker sections.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 450000, "minPercentage": 60, "educationLevels": ["pg"], "gender": "all"},
            "deadline": d(130), "applyLink": "https://scholarships.gov.in",
            "documents": ["UG marksheet (60%+)", "Income certificate", "Aadhaar", "PG admission proof"],
            "tags": ["pg", "ugc", "merit", "nspg"],
        },
        {
            "source_id": "ugc_maulana_azad_fellowship",
            "name": "Maulana Azad National Fellowship for Minority Students",
            "source": "UGC",
            "amount": 372000,
            "description": "Five-year fellowship for minority students pursuing M.Phil and PhD. JRF ₹31,000/month + SRF ₹35,000/month.",
            "eligibility": {"categories": ["minority"], "states": ["all"], "maxIncome": 600000, "minPercentage": 0, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(130), "applyLink": "https://maef.nic.in",
            "documents": ["Minority certificate", "PG marksheets", "Research proposal", "Aadhaar", "Income certificate"],
            "tags": ["minority", "phd", "fellowship", "ugc", "research"],
        },
        {
            "source_id": "ugc_rajiv_gandhi_national",
            "name": "Rajiv Gandhi National Fellowship for SC/ST",
            "source": "UGC",
            "amount": 372000,
            "description": "For SC/ST students pursuing M.Phil/PhD. JRF ₹31,000/month for 2 years, SRF ₹35,000/month for 3 years.",
            "eligibility": {"categories": ["sc", "st"], "states": ["all"], "maxIncome": 0, "minPercentage": 0, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(140), "applyLink": "https://scholarships.gov.in",
            "documents": ["Caste certificate", "PG degree certificate", "NET/SET qualification", "Aadhaar"],
            "tags": ["sc", "st", "phd", "fellowship", "ugc", "rajiv gandhi"],
        },
        {
            "source_id": "csir_jrf",
            "name": "CSIR-UGC NET Junior Research Fellowship (JRF)",
            "source": "CSIR",
            "amount": 372000,
            "description": "For students pursuing PhD in science through CSIR-UGC NET exam. ₹31,000/month JRF + HRA.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 55, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(150), "applyLink": "https://csirhrdg.res.in",
            "documents": ["CSIR NET scorecard", "PG marksheet (55%+)", "Aadhaar", "Research admission proof"],
            "tags": ["science", "phd", "csir", "net", "research", "jrf"],
        },
        {
            "source_id": "dbt_jrf",
            "name": "DBT-JRF Biotechnology Research Fellowship",
            "source": "DBT - Government of India",
            "amount": 372000,
            "description": "For students pursuing PhD in biotechnology through DBT-JRF exam. ₹31,000/month for 2 years.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(160), "applyLink": "https://www.dbtjrf.res.in",
            "documents": ["DBT-JRF scorecard", "PG marksheet (60%+)", "Aadhaar", "Research institution letter"],
            "tags": ["biotechnology", "phd", "dbt", "research", "jrf"],
        },
        {
            "source_id": "icmr_jrf",
            "name": "ICMR Junior Research Fellowship (JRF)",
            "source": "ICMR",
            "amount": 372000,
            "description": "For students pursuing biomedical research PhD through ICMR competitive exam.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 55, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(150), "applyLink": "https://www.icmr.gov.in",
            "documents": ["ICMR JRF scorecard", "PG marksheet", "Aadhaar", "Research institution letter"],
            "tags": ["medical", "biomedical", "phd", "icmr", "research"],
        },
    ]


# ── 3. INSPIRE & DST ────────────────────────────────────

def get_dst_inspire() -> List[Dict]:
    return [
        {
            "source_id": "inspire_she",
            "name": "INSPIRE Scholarship for Higher Education (SHE)",
            "source": "DST - Government of India",
            "amount": 80000,
            "description": "For students in top 1% of Class XII board results pursuing natural sciences at B.Sc/B.S/Integrated M.Sc level.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 90, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://online-inspire.gov.in",
            "documents": ["Class XII marksheet (top 1%)", "Aadhaar", "Science admission proof", "Bank passbook"],
            "tags": ["dst", "science", "merit", "inspire", "top ranker"],
        },
        {
            "source_id": "inspire_fellowship_phd",
            "name": "INSPIRE Fellowship for PhD",
            "source": "DST - Government of India",
            "amount": 420000,
            "description": "For students pursuing PhD in natural and applied sciences. ₹35,000/month + ₹70,000 research grant per year.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 75, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(150), "applyLink": "https://online-inspire.gov.in",
            "documents": ["PG marksheet (75%+)", "GATE/NET/JEST scorecard or direct from top institutions", "Aadhaar"],
            "tags": ["science", "phd", "dst", "inspire", "fellowship"],
        },
        {
            "source_id": "kvpy_fellowship",
            "name": "KVPY - Kishore Vaigyanik Protsahan Yojana",
            "source": "DST via IISc Bangalore",
            "amount": 84000,
            "description": "For students with aptitude for research in science. ₹7,000/month for UG + ₹9,000/month for PG/PhD.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 75, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://kvpy.iisc.ernet.in",
            "documents": ["Class XII/UG marksheet (75%+)", "KVPY aptitude test scorecard", "Aadhaar"],
            "tags": ["science", "research", "kvpy", "dst", "iisc"],
        },
        {
            "source_id": "ntse_scholarship",
            "name": "NTSE - National Talent Search Examination",
            "source": "NCERT",
            "amount": 24000,
            "description": "For talented Class 10 students. ₹1,250/month for Class 11-12, ₹2,000/month for UG/PG, ₹4,000/month for PhD.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["11th", "12th", "ug"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://ncert.nic.in",
            "documents": ["Class X NTSE scorecard", "Class X marksheet", "Aadhaar", "School certificate"],
            "tags": ["talent", "ncert", "ntse", "merit", "school"],
        },
    ]


# ── 4. CBSE & NTA ────────────────────────────────────────

def get_cbse_nta() -> List[Dict]:
    return [
        {
            "source_id": "cbse_merit_single_girl",
            "name": "CBSE Merit Scholarship for Single Girl Child",
            "source": "CBSE",
            "amount": 6000,
            "description": "For single girl child who passed CBSE Class X with 60%+ and is studying in CBSE Class XI-XII.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["11th", "12th"], "gender": "female"},
            "deadline": d(140), "applyLink": "https://cbse.gov.in/cbsenew/scholarships.html",
            "documents": ["Class X marksheet (60%+)", "Single girl child affidavit", "Aadhaar", "School certificate"],
            "tags": ["cbse", "girl", "single child", "merit"],
        },
        {
            "source_id": "cbse_merit_wards",
            "name": "CBSE Scholarship for Wards of Armed Forces",
            "source": "CBSE",
            "amount": 6000,
            "description": "For wards of defence service personnel (Army, Navy, Air Force) studying in CBSE affiliated schools.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["11th", "12th"], "gender": "all"},
            "deadline": d(140), "applyLink": "https://cbse.gov.in",
            "documents": ["Parent service certificate", "Class X marksheet (60%+)", "Aadhaar", "School bonafide"],
            "tags": ["cbse", "armed forces", "defence", "school"],
        },
    ]


# ── 5. STATE GOVERNMENT - SOUTH ──────────────────────────

def get_state_south() -> List[Dict]:
    return [
        # Tamil Nadu
        {
            "source_id": "tn_sc_first_gen",
            "name": "Tamil Nadu First Generation Graduate Scholarship",
            "source": "Tamil Nadu Government",
            "amount": 24000,
            "description": "For first-generation graduates from SC/ST families in Tamil Nadu pursuing UG courses.",
            "eligibility": {"categories": ["sc", "st"], "states": ["Tamil Nadu"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://tnscholarships.gov.in",
            "documents": ["Caste certificate", "First generation declaration", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["tamil nadu", "sc", "st", "first generation"],
        },
        {
            "source_id": "tn_bc_mbc",
            "name": "Tamil Nadu BC/MBC Scholarship",
            "source": "Tamil Nadu Government",
            "amount": 18000,
            "description": "Scholarship for BC/MBC students in Tamil Nadu pursuing higher education.",
            "eligibility": {"categories": ["obc"], "states": ["Tamil Nadu"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://tnscholarships.gov.in",
            "documents": ["Community certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["tamil nadu", "obc", "bc", "mbc"],
        },
        {
            "source_id": "tn_ews_scholarship",
            "name": "Tamil Nadu EWS Scholarship",
            "source": "Tamil Nadu Government",
            "amount": 15000,
            "description": "Scholarship for economically weaker section general category students in Tamil Nadu.",
            "eligibility": {"categories": ["ews", "general"], "states": ["Tamil Nadu"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["ug", "diploma"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://tnscholarships.gov.in",
            "documents": ["EWS certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["tamil nadu", "ews", "general"],
        },
        {
            "source_id": "tn_minority_scholarship",
            "name": "Tamil Nadu Minority Scholarship",
            "source": "Tamil Nadu Government",
            "amount": 10000,
            "description": "For minority students in Tamil Nadu pursuing school and higher education.",
            "eligibility": {"categories": ["minority"], "states": ["Tamil Nadu"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["ug", "pg", "11th", "12th"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://tnscholarships.gov.in",
            "documents": ["Minority certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["tamil nadu", "minority"],
        },
        {
            "source_id": "tn_girl_student_transport",
            "name": "Tamil Nadu Free Bus Pass for Girl Students",
            "source": "Tamil Nadu Government",
            "amount": 5000,
            "description": "Free bus pass equivalent for girl students pursuing higher education in Tamil Nadu government institutions.",
            "eligibility": {"categories": ["all"], "states": ["Tamil Nadu"], "maxIncome": 0, "minPercentage": 0, "educationLevels": ["ug", "diploma"], "gender": "female"},
            "deadline": d(90), "applyLink": "https://tnscholarships.gov.in",
            "documents": ["College ID", "Aadhaar", "Address proof (Tamil Nadu)"],
            "tags": ["tamil nadu", "girl", "transport"],
        },
        {
            "source_id": "tn_sc_hostellers",
            "name": "Tamil Nadu SC Hostellers Scholarship",
            "source": "Tamil Nadu Government",
            "amount": 30000,
            "description": "Additional scholarship for SC students staying in hostels for higher education in Tamil Nadu.",
            "eligibility": {"categories": ["sc"], "states": ["Tamil Nadu"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://tnscholarships.gov.in",
            "documents": ["Caste certificate", "Hostel certificate", "Income certificate", "Aadhaar"],
            "tags": ["tamil nadu", "sc", "hostel"],
        },
        # Kerala
        {
            "source_id": "kerala_sc_scholarship",
            "name": "Kerala SC Development Scholarship",
            "source": "Kerala Government",
            "amount": 20000,
            "description": "For SC students in Kerala pursuing higher education at UG and PG level.",
            "eligibility": {"categories": ["sc"], "states": ["Kerala"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://www.scholarship.kerala.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["kerala", "sc"],
        },
        {
            "source_id": "kerala_st_scholarship",
            "name": "Kerala Tribal Development Scholarship",
            "source": "Kerala Government",
            "amount": 24000,
            "description": "For ST students in Kerala with enhanced support for tribal communities pursuing higher education.",
            "eligibility": {"categories": ["st"], "states": ["Kerala"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://www.scholarship.kerala.gov.in",
            "documents": ["Tribal certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["kerala", "st", "tribal"],
        },
        {
            "source_id": "kerala_obc_scholarship",
            "source": "Kerala Government",
            "name": "Kerala OBC Scholarship",
            "amount": 15000,
            "description": "For OBC students in Kerala pursuing UG and PG education.",
            "eligibility": {"categories": ["obc"], "states": ["Kerala"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://www.scholarship.kerala.gov.in",
            "documents": ["OBC certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["kerala", "obc"],
        },
        # Andhra Pradesh
        {
            "source_id": "ap_jagananna_vasathi",
            "name": "Jagananna Vasathi Deevena Scholarship",
            "source": "Andhra Pradesh Government",
            "amount": 20000,
            "description": "AP scholarship covering hostel and mess fees for BC/SC/ST/EBC students.",
            "eligibility": {"categories": ["sc", "st", "obc", "ews"], "states": ["Andhra Pradesh"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://navasakam.ap.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Aadhaar", "Hostel certificate"],
            "tags": ["andhra pradesh", "sc", "st", "obc", "hostel"],
        },
        {
            "source_id": "ap_sc_postmatric",
            "name": "Andhra Pradesh SC Post Matric Scholarship",
            "source": "Andhra Pradesh Government",
            "amount": 18000,
            "description": "For SC students in AP pursuing post-matric education including professional courses.",
            "eligibility": {"categories": ["sc"], "states": ["Andhra Pradesh"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://apepass.cgg.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["andhra pradesh", "sc", "postmatric"],
        },
        {
            "source_id": "ap_bc_welfare",
            "name": "Andhra Pradesh BC Welfare Scholarship",
            "source": "Andhra Pradesh Government",
            "amount": 15000,
            "description": "For BC category students in AP pursuing higher education and professional courses.",
            "eligibility": {"categories": ["obc"], "states": ["Andhra Pradesh"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://apepass.cgg.gov.in",
            "documents": ["BC certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["andhra pradesh", "obc", "bc"],
        },
        # Telangana
        {
            "source_id": "ts_sc_postmatric",
            "name": "Telangana SC Post Matric Scholarship",
            "source": "Telangana Government",
            "amount": 18000,
            "description": "For SC students in Telangana pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Telangana"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://telanganaepass.cgg.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["telangana", "sc"],
        },
        {
            "source_id": "ts_bc_scholarship",
            "name": "Telangana BC Welfare Scholarship",
            "source": "Telangana Government",
            "amount": 15000,
            "description": "For BC students in Telangana pursuing higher education.",
            "eligibility": {"categories": ["obc"], "states": ["Telangana"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://telanganaepass.cgg.gov.in",
            "documents": ["BC certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["telangana", "obc", "bc"],
        },
        # Karnataka
        {
            "source_id": "karnataka_ssp_sc",
            "name": "Karnataka SSP SC Post Matric Scholarship",
            "source": "Karnataka Government",
            "amount": 22000,
            "description": "State scholarship portal for SC students in Karnataka pursuing higher education.",
            "eligibility": {"categories": ["sc"], "states": ["Karnataka"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://ssp.postmatric.karnataka.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Aadhaar", "Marksheet", "Bank passbook"],
            "tags": ["karnataka", "sc"],
        },
        {
            "source_id": "karnataka_ssp_obc",
            "name": "Karnataka SSP OBC Post Matric Scholarship",
            "source": "Karnataka Government",
            "amount": 18000,
            "description": "For OBC students in Karnataka pursuing post-matric education.",
            "eligibility": {"categories": ["obc"], "states": ["Karnataka"], "maxIncome": 150000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://ssp.postmatric.karnataka.gov.in",
            "documents": ["OBC certificate", "Income certificate", "Aadhaar", "Marksheet"],
            "tags": ["karnataka", "obc"],
        },
        {
            "source_id": "karnataka_dr_br_ambedkar",
            "name": "Karnataka Dr. B.R. Ambedkar Overseas Study Scholarship",
            "source": "Karnataka Government",
            "amount": 2500000,
            "description": "For SC students from Karnataka to pursue Masters abroad at top 200 world-ranked universities.",
            "eligibility": {"categories": ["sc"], "states": ["Karnataka"], "maxIncome": 600000, "minPercentage": 60, "educationLevels": ["pg"], "gender": "all"},
            "deadline": d(130), "applyLink": "https://sw.kar.nic.in",
            "documents": ["Caste certificate", "Income certificate", "UG marksheet (60%+)", "University admission letter abroad"],
            "tags": ["karnataka", "sc", "abroad", "overseas", "masters"],
        },
    ]


# ── 6. STATE GOVERNMENT - NORTH & WEST ──────────────────

def get_state_north_west() -> List[Dict]:
    return [
        # Maharashtra
        {
            "source_id": "maha_eklavya_st",
            "name": "Maharashtra Eklavya Scholarship for ST Students",
            "source": "Maharashtra Government",
            "amount": 25000,
            "description": "For ST students in Maharashtra pursuing professional courses like engineering, medicine, law.",
            "eligibility": {"categories": ["st"], "states": ["Maharashtra"], "maxIncome": 250000, "minPercentage": 50, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://mahadbt.maharashtra.gov.in",
            "documents": ["Tribal certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["maharashtra", "st", "tribal"],
        },
        {
            "source_id": "maha_sc_scholarship",
            "name": "Maharashtra SC Post Matric Scholarship",
            "source": "Maharashtra Government",
            "amount": 20000,
            "description": "For SC students in Maharashtra pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Maharashtra"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://mahadbt.maharashtra.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["maharashtra", "sc"],
        },
        {
            "source_id": "maha_obc_scholarship",
            "name": "Maharashtra OBC Post Matric Scholarship",
            "source": "Maharashtra Government",
            "amount": 15000,
            "description": "For OBC students in Maharashtra pursuing post-matric education.",
            "eligibility": {"categories": ["obc"], "states": ["Maharashtra"], "maxIncome": 100000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://mahadbt.maharashtra.gov.in",
            "documents": ["OBC certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["maharashtra", "obc"],
        },
        # Uttar Pradesh
        {
            "source_id": "up_prematric_scholarship",
            "name": "Uttar Pradesh Pre Matric Scholarship",
            "source": "Uttar Pradesh Government",
            "amount": 8000,
            "description": "For SC/ST/OBC/Minority/General students in UP studying in Class 9-10.",
            "eligibility": {"categories": ["sc", "st", "obc", "minority", "general"], "states": ["Uttar Pradesh"], "maxIncome": 100000, "minPercentage": 0, "educationLevels": ["9th", "10th"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://scholarship.up.gov.in",
            "documents": ["Category certificate", "Income certificate", "Aadhaar", "School certificate"],
            "tags": ["uttar pradesh", "prematric", "school"],
        },
        {
            "source_id": "up_postmatric_scholarship",
            "name": "Uttar Pradesh Post Matric Scholarship",
            "source": "Uttar Pradesh Government",
            "amount": 15000,
            "description": "For SC/ST/OBC/Minority/General UP domicile students studying at post-matric level.",
            "eligibility": {"categories": ["sc", "st", "obc", "minority", "general"], "states": ["Uttar Pradesh"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(115), "applyLink": "https://scholarship.up.gov.in",
            "documents": ["Category certificate", "Income certificate", "Aadhaar", "Marksheet"],
            "tags": ["uttar pradesh", "postmatric"],
        },
        # Rajasthan
        {
            "source_id": "rajasthan_sc_scholarship",
            "name": "Rajasthan SC Post Matric Scholarship",
            "source": "Rajasthan Government",
            "amount": 15000,
            "description": "For SC students in Rajasthan pursuing post-matric courses.",
            "eligibility": {"categories": ["sc"], "states": ["Rajasthan"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://sje.rajasthan.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["rajasthan", "sc"],
        },
        {
            "source_id": "rajasthan_devnarayan_girl",
            "name": "Rajasthan Devnarayan Girl Student Scholarship",
            "source": "Rajasthan Government",
            "amount": 15000,
            "description": "For girl students from backward class families in Rajasthan pursuing Class 11 to PG education.",
            "eligibility": {"categories": ["obc"], "states": ["Rajasthan"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "female"},
            "deadline": d(100), "applyLink": "https://hte.rajasthan.gov.in",
            "documents": ["BC certificate", "Income certificate", "Marksheet (50%+)", "Aadhaar", "Girl declaration"],
            "tags": ["rajasthan", "girl", "obc", "devnarayan"],
        },
        {
            "source_id": "rajasthan_mukhyamantri_ucch_shiksha",
            "name": "Rajasthan Mukhyamantri Ucch Shiksha Scholarship",
            "source": "Rajasthan Government",
            "amount": 10000,
            "description": "For Rajasthan domicile students from any category who scored 60%+ in Class XII Board exams.",
            "eligibility": {"categories": ["all"], "states": ["Rajasthan"], "maxIncome": 250000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://hte.rajasthan.gov.in",
            "documents": ["Class XII marksheet (60%+)", "Income certificate", "Aadhaar", "Domicile certificate"],
            "tags": ["rajasthan", "merit", "all categories"],
        },
        # Gujarat
        {
            "source_id": "gujarat_sc_scholarship",
            "name": "Gujarat SC Post Matric Scholarship",
            "source": "Gujarat Government",
            "amount": 18000,
            "description": "For SC students in Gujarat pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Gujarat"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://esamajkalyan.gujarat.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["gujarat", "sc"],
        },
        {
            "source_id": "gujarat_st_scholarship",
            "name": "Gujarat ST Post Matric Scholarship",
            "source": "Gujarat Government",
            "amount": 20000,
            "description": "For ST students in Gujarat pursuing post-matric education with enhanced support.",
            "eligibility": {"categories": ["st"], "states": ["Gujarat"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(105), "applyLink": "https://esamajkalyan.gujarat.gov.in",
            "documents": ["Tribal certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["gujarat", "st", "tribal"],
        },
        # Delhi
        {
            "source_id": "delhi_sc_scholarship",
            "name": "Delhi SC Post Matric Scholarship",
            "source": "Delhi Government",
            "amount": 16000,
            "description": "For SC students in Delhi pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Delhi"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://edistrict.delhigovt.nic.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["delhi", "sc"],
        },
        {
            "source_id": "delhi_minority_scholarship",
            "name": "Delhi Minority Scholarship",
            "source": "Delhi Government",
            "amount": 12000,
            "description": "For minority students in Delhi pursuing post-matric education.",
            "eligibility": {"categories": ["minority"], "states": ["Delhi"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://edistrict.delhigovt.nic.in",
            "documents": ["Minority certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["delhi", "minority"],
        },
    ]


# ── 7. STATE GOVERNMENT - EAST & NORTH EAST ─────────────

def get_state_east() -> List[Dict]:
    return [
        # West Bengal
        {
            "source_id": "wb_svmcm",
            "name": "West Bengal Swami Vivekananda Merit-cum-Means Scholarship",
            "source": "West Bengal Government",
            "amount": 60000,
            "description": "For meritorious students from economically backward classes in WB pursuing higher education.",
            "eligibility": {"categories": ["all"], "states": ["West Bengal"], "maxIncome": 250000, "minPercentage": 75, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://svmcm.wbhed.gov.in",
            "documents": ["Marksheet (75%+)", "Income certificate", "Aadhaar", "Admission proof"],
            "tags": ["west bengal", "merit", "vivekananda"],
        },
        {
            "source_id": "wb_aikyashree",
            "name": "West Bengal Aikyashree Scholarship",
            "source": "West Bengal Government",
            "amount": 10000,
            "description": "For minority students in West Bengal pursuing education at all levels.",
            "eligibility": {"categories": ["minority"], "states": ["West Bengal"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["9th", "10th", "11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://wbmdfcscholarship.in",
            "documents": ["Minority certificate", "Income certificate", "Aadhaar", "Marksheet"],
            "tags": ["west bengal", "minority", "aikyashree"],
        },
        {
            "source_id": "wb_sc_scholarship",
            "name": "West Bengal SC Scholarship",
            "source": "West Bengal Government",
            "amount": 18000,
            "description": "For SC students in West Bengal pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["West Bengal"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarshipportal.wb.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["west bengal", "sc"],
        },
        # Bihar
        {
            "source_id": "bihar_sc_postmatric",
            "name": "Bihar SC Post Matric Scholarship",
            "source": "Bihar Government",
            "amount": 15000,
            "description": "For SC students in Bihar pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Bihar"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://pmsonline.bih.nic.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["bihar", "sc"],
        },
        {
            "source_id": "bihar_combined_scholarship",
            "name": "Bihar Combined (Mukhyamantri) Scholarship",
            "source": "Bihar Government",
            "amount": 25000,
            "description": "Mukhyamantri Kanya Utthan Yojana for girl students in Bihar pursuing graduation.",
            "eligibility": {"categories": ["all"], "states": ["Bihar"], "maxIncome": 0, "minPercentage": 0, "educationLevels": ["ug"], "gender": "female"},
            "deadline": d(110), "applyLink": "https://medhasoft.bih.nic.in",
            "documents": ["Income certificate", "Marksheet", "Aadhaar", "Bank passbook", "College enrollment proof"],
            "tags": ["bihar", "girl", "kanya utthan"],
        },
        # Odisha
        {
            "source_id": "odisha_sc_scholarship",
            "name": "Odisha SC/ST Post Matric Scholarship",
            "source": "Odisha Government",
            "amount": 18000,
            "description": "For SC/ST students in Odisha pursuing post-matric education.",
            "eligibility": {"categories": ["sc", "st"], "states": ["Odisha"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarships.odisha.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["odisha", "sc", "st"],
        },
        {
            "source_id": "odisha_medhabruti",
            "name": "Odisha State Merit Scholarship (Medhabruti)",
            "source": "Odisha Government",
            "amount": 15000,
            "description": "For meritorious students from Odisha who scored 60%+ in Class X or XII board exams.",
            "eligibility": {"categories": ["all"], "states": ["Odisha"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["11th", "12th", "ug"], "gender": "all"},
            "deadline": d(95), "applyLink": "https://scholarships.odisha.gov.in",
            "documents": ["Board marksheet (60%+)", "Aadhaar", "Domicile certificate", "Admission proof"],
            "tags": ["odisha", "merit", "medhabruti"],
        },
        # Assam
        {
            "source_id": "assam_sc_scholarship",
            "name": "Assam SC Post Matric Scholarship",
            "source": "Assam Government",
            "amount": 15000,
            "description": "For SC students in Assam pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Assam"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://nbcfdc.gov.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["assam", "sc"],
        },
        # Madhya Pradesh
        {
            "source_id": "mp_sc_postmatric",
            "name": "Madhya Pradesh SC Post Matric Scholarship",
            "source": "Madhya Pradesh Government",
            "amount": 17000,
            "description": "For SC students in MP pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Madhya Pradesh"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarshipportal.mp.nic.in",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["madhya pradesh", "sc"],
        },
        {
            "source_id": "mp_obc_scholarship",
            "name": "Madhya Pradesh OBC Post Matric Scholarship",
            "source": "Madhya Pradesh Government",
            "amount": 12000,
            "description": "For OBC students in MP pursuing post-matric education.",
            "eligibility": {"categories": ["obc"], "states": ["Madhya Pradesh"], "maxIncome": 100000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarshipportal.mp.nic.in",
            "documents": ["OBC certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["madhya pradesh", "obc"],
        },
        # Punjab
        {
            "source_id": "punjab_sc_scholarship",
            "name": "Punjab Post Matric Scholarship for SC Students",
            "source": "Punjab Government",
            "amount": 15000,
            "description": "For SC students in Punjab pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Punjab"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://punjab.gov.in/scholarship",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["punjab", "sc"],
        },
        # Haryana
        {
            "source_id": "haryana_sc_scholarship",
            "name": "Haryana SC Post Matric Scholarship",
            "source": "Haryana Government",
            "amount": 18000,
            "description": "For SC students in Haryana pursuing post-matric education.",
            "eligibility": {"categories": ["sc"], "states": ["Haryana"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://haryana.gov.in/scholarship",
            "documents": ["Caste certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["haryana", "sc"],
        },
        {
            "source_id": "haryana_har_chhatravritti",
            "name": "Haryana Har Chhatravritti Scholarship",
            "source": "Haryana Government",
            "amount": 12000,
            "description": "For all Haryana domicile students studying at UG level in Haryana government colleges.",
            "eligibility": {"categories": ["all"], "states": ["Haryana"], "maxIncome": 180000, "minPercentage": 0, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://harchhatravritti.haryana.gov.in",
            "documents": ["Domicile certificate", "Income certificate", "Aadhaar", "College enrollment proof"],
            "tags": ["haryana", "all categories", "ug"],
        },
    ]


# ── 8. PRIVATE & CORPORATE ──────────────────────────────

def get_private_corporate() -> List[Dict]:
    return [
        {
            "source_id": "tata_capital_pankh",
            "name": "Tata Capital Pankh Scholarship",
            "source": "Tata Trusts",
            "amount": 50000,
            "description": "For meritorious students from underprivileged backgrounds pursuing professional/vocational UG courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 400000, "minPercentage": 60, "educationLevels": ["ug", "diploma"], "gender": "all"},
            "deadline": d(75), "applyLink": "https://www.buddy4study.com/scholarship/tata-capital-pankh-scholarship-program",
            "documents": ["Income certificate", "Marksheet (60%+)", "Aadhaar", "Admission proof", "Bank passbook"],
            "tags": ["tata", "merit", "private"],
        },
        {
            "source_id": "reliance_foundation_ug",
            "name": "Reliance Foundation Undergraduate Scholarship",
            "source": "Reliance Foundation",
            "amount": 200000,
            "description": "For outstanding UG students in engineering, humanities, science, commerce with mentoring support.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 1500000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://www.reliancefoundation.org/scholarships",
            "documents": ["Marksheet (60%+)", "Aadhaar", "Income proof", "Admission letter"],
            "tags": ["reliance", "merit", "ug"],
        },
        {
            "source_id": "reliance_foundation_pg",
            "name": "Reliance Foundation Postgraduate Scholarship",
            "source": "Reliance Foundation",
            "amount": 200000,
            "description": "For PG students in science, technology, engineering, mathematics and professional courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 1500000, "minPercentage": 60, "educationLevels": ["pg"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://www.reliancefoundation.org/scholarships",
            "documents": ["UG marksheet (60%+)", "Aadhaar", "Income proof", "PG admission letter"],
            "tags": ["reliance", "merit", "pg"],
        },
        {
            "source_id": "hdfc_ecss",
            "name": "HDFC Bank Educational Crisis Scholarship",
            "source": "HDFC Bank",
            "amount": 75000,
            "description": "For students facing sudden financial crisis due to loss of parent/guardian income.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 500000, "minPercentage": 55, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://www.hdfcbank.com/personal/pay/donations/educational-crisis-scholarship-support",
            "documents": ["Income certificate", "Marksheet (55%+)", "Aadhaar", "Bank statement"],
            "tags": ["hdfc", "crisis", "financial need"],
        },
        {
            "source_id": "vidyasaarathi_infosys",
            "name": "Vidyasaarathi Infosys BPM Scholarship",
            "source": "Vidyasaarathi - Infosys BPM",
            "amount": 30000,
            "description": "For students pursuing graduation from recognized universities across India.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 600000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://www.vidyasaarathi.co.in",
            "documents": ["Marksheet (60%+)", "Income certificate", "Aadhaar", "College ID"],
            "tags": ["infosys", "vidyasaarathi", "ug"],
        },
        {
            "source_id": "aditya_birla_scholarship",
            "name": "Aditya Birla Scholarship",
            "source": "Aditya Birla Group",
            "amount": 65000,
            "description": "Prestigious merit-based scholarship for students at IITs, IIMs, BITS Pilani, XLRI, and top law colleges.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 80, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://www.adityabirlascholars.net",
            "documents": ["Marksheet (80%+)", "Admission letter from top institution", "Aadhaar", "Essay"],
            "tags": ["aditya birla", "merit", "iit", "iim", "bits"],
        },
        {
            "source_id": "kotak_kanya_scholarship",
            "name": "Kotak Kanya Scholarship",
            "source": "Kotak Education Foundation",
            "amount": 150000,
            "description": "For meritorious girl students from low-income families pursuing first year of UG professional courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 600000, "minPercentage": 75, "educationLevels": ["ug"], "gender": "female"},
            "deadline": d(75), "applyLink": "https://kotakeducation.org",
            "documents": ["Class XII marksheet (75%+)", "Income certificate", "Aadhaar", "Admission proof"],
            "tags": ["kotak", "girl", "merit", "ug", "professional"],
        },
        {
            "source_id": "sitaram_jindal_scholarship",
            "name": "Sitaram Jindal Foundation Scholarship",
            "source": "Sitaram Jindal Foundation",
            "amount": 24000,
            "description": "For meritorious and needy students in government/aided colleges across India.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 250000, "minPercentage": 55, "educationLevels": ["ug", "pg", "diploma"], "gender": "all"},
            "deadline": d(70), "applyLink": "https://sitaramjindalfoundation.org",
            "documents": ["Income certificate", "Marksheet (55%+)", "Aadhaar", "College bonafide"],
            "tags": ["jindal", "merit-cum-means"],
        },
        {
            "source_id": "iocl_scholarship",
            "name": "Indian Oil Educational Scholarship Scheme",
            "source": "Indian Oil Corporation (IOCL)",
            "amount": 30000,
            "description": "For meritorious SC/ST/OBC students pursuing engineering, MBBS, or MBA courses.",
            "eligibility": {"categories": ["sc", "st", "obc"], "states": ["all"], "maxIncome": 500000, "minPercentage": 60, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://iocl.com/scholarship",
            "documents": ["Caste certificate", "Income certificate", "Marksheet (60%+)", "Aadhaar", "Admission proof"],
            "tags": ["iocl", "indian oil", "sc", "st", "obc", "professional"],
        },
        {
            "source_id": "ongc_scholarship",
            "name": "ONGC Foundation Scholarship",
            "source": "ONGC Foundation",
            "amount": 48000,
            "description": "For SC/ST meritorious students pursuing professional UG courses at recognized institutes.",
            "eligibility": {"categories": ["sc", "st"], "states": ["all"], "maxIncome": 450000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(85), "applyLink": "https://www.ongcindia.com",
            "documents": ["Caste certificate", "Income certificate", "Marksheet (60%+)", "Aadhaar", "Admission proof"],
            "tags": ["ongc", "sc", "st", "merit", "psu"],
        },
        {
            "source_id": "lt_scholarship",
            "name": "L&T Build India Scholarship",
            "source": "Larsen & Toubro",
            "amount": 60000,
            "description": "For students from economically weaker backgrounds pursuing engineering and technical courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 600000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://www.buddy4study.com/scholarship/lt-build-india-scholarship",
            "documents": ["Income certificate", "Marksheet (60%+)", "Aadhaar", "Engineering admission proof"],
            "tags": ["l&t", "engineering", "technical"],
        },
        {
            "source_id": "swami_dayanand_scholarship",
            "name": "Swami Dayanand Education Foundation Scholarship",
            "source": "Swami Dayanand Education Foundation",
            "amount": 50000,
            "description": "For first-year B.Tech/MBBS students with JEE/NEET qualification from low-income families.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 1200000, "minPercentage": 80, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(70), "applyLink": "https://www.swamidayanand.org/scholarship-india",
            "documents": ["Class XII marksheet (80%+)", "JEE/NEET scorecard", "Income certificate", "Aadhaar"],
            "tags": ["engineering", "medical", "jee", "neet", "merit"],
        },
        {
            "source_id": "rolls_royce_unnati",
            "name": "Rolls-Royce Unnati Scholarship",
            "source": "Rolls-Royce",
            "amount": 35000,
            "description": "For meritorious SC/ST students pursuing engineering at top institutes across India.",
            "eligibility": {"categories": ["sc", "st"], "states": ["all"], "maxIncome": 800000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(75), "applyLink": "https://www.buddy4study.com/scholarship/rolls-royce-unnati-scholarship",
            "documents": ["Caste certificate", "Marksheet (60%+)", "Aadhaar", "Engineering admission proof"],
            "tags": ["rolls royce", "sc", "st", "engineering"],
        },
        {
            "source_id": "virtusa_engineering_excellence",
            "name": "Virtusa Engineering Excellence Scholarship",
            "source": "Virtusa Foundation",
            "amount": 50000,
            "description": "For engineering students from economically weaker backgrounds pursuing technical education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 500000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(70), "applyLink": "https://www.buddy4study.com/scholarship/virtusa-engineering-excellence-scholarship",
            "documents": ["Income certificate", "Marksheet (60%+)", "Aadhaar", "Engineering admission proof"],
            "tags": ["virtusa", "engineering", "it"],
        },
        {
            "source_id": "adani_scholarship",
            "name": "Adani Foundation Scholarship",
            "source": "Adani Foundation",
            "amount": 100000,
            "description": "For students pursuing engineering, medical, law, and management professional courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 600000, "minPercentage": 60, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://adanifoundation.org",
            "documents": ["Income certificate", "Marksheet (60%+)", "Aadhaar", "Professional course admission proof"],
            "tags": ["adani", "professional", "engineering", "medical"],
        },
        {
            "source_id": "narotam_sekhsaria_pg",
            "name": "Narotam Sekhsaria Foundation PG Scholarship",
            "source": "Narotam Sekhsaria Foundation",
            "amount": 1500000,
            "description": "Merit-cum-means scholarship for Indian citizens pursuing PG studies at top Indian or foreign universities.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["pg"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://www.nsfoundation.co.in",
            "documents": ["UG marksheet (60%+)", "Income statement", "Aadhaar", "PG admission offer letter"],
            "tags": ["narotam sekhsaria", "pg", "abroad", "merit"],
        },
        {
            "source_id": "kc_mahindra_pg_abroad",
            "name": "KC Mahindra Scholarship for PG Studies Abroad",
            "source": "KC Mahindra Education Trust",
            "amount": 1000000,
            "description": "For Indian students pursuing postgraduate studies at top universities abroad.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["pg"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://kcmet.org",
            "documents": ["UG marksheet (60%+)", "Abroad university admission letter", "Aadhaar", "Income statement"],
            "tags": ["mahindra", "pg", "abroad", "international"],
        },
        {
            "source_id": "loreal_india_girl_science",
            "name": "L'Oréal India For Young Women in Science Scholarship",
            "source": "L'Oréal India",
            "amount": 250000,
            "description": "For girl students pursuing science at UG level at top Indian universities.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 85, "educationLevels": ["ug"], "gender": "female"},
            "deadline": d(65), "applyLink": "https://www.loreal.com/en/india/articles/commitments/l_oreal-india-for-young-women-in-science",
            "documents": ["Class XII marksheet (85%+)", "Science UG admission proof", "Aadhaar", "Essay on scientific interest"],
            "tags": ["loreal", "girl", "science", "merit"],
        },
        {
            "source_id": "atul_maheshwari_scholarship",
            "name": "Atul Maheshwari Scholarship",
            "source": "Amar Ujala Foundation",
            "amount": 100000,
            "description": "For academically meritorious students from economically disadvantaged backgrounds pursuing higher education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 200000, "minPercentage": 70, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(70), "applyLink": "https://www.buddy4study.com/scholarship/atul-maheshwari-scholarship",
            "documents": ["Income certificate", "Marksheet (70%+)", "Aadhaar", "Admission proof"],
            "tags": ["amar ujala", "merit", "ug"],
        },
        {
            "source_id": "mmc_scholarship_india",
            "name": "MakeMyTrip Padhte Raho Badhte Raho Scholarship",
            "source": "MakeMyTrip Foundation",
            "amount": 50000,
            "description": "For students who lost a parent during COVID-19 pandemic and are pursuing higher education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 500000, "minPercentage": 55, "educationLevels": ["ug", "diploma"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://www.buddy4study.com/scholarship/makemytrip-foundation-padhte-raho-badhte-raho-scholarship",
            "documents": ["Parent death certificate (COVID)", "Income certificate", "Marksheet (55%+)", "Aadhaar"],
            "tags": ["makemytrip", "covid orphan", "financial need"],
        },
        {
            "source_id": "inlaks_scholarship",
            "name": "Inlaks Scholarship",
            "source": "Inlaks Shivdasani Foundation",
            "amount": 5000000,
            "description": "For high-achieving Indian students (under 30) pursuing Masters/PhD abroad at top world-ranked universities.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 65, "educationLevels": ["pg", "phd"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://inlaksfoundation.org/opportunities/scholarship",
            "documents": ["UG/PG marksheet (65%+)", "Foreign university admission letter", "Research proposal", "References"],
            "tags": ["inlaks", "abroad", "masters", "phd", "international"],
        },
        {
            "source_id": "jn_tata_endowment",
            "name": "JN Tata Endowment Loan Scholarship",
            "source": "JN Tata Endowment",
            "amount": 1000000,
            "description": "Merit-based loan scholarship for Indian students pursuing higher studies abroad.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["pg", "phd"], "gender": "all"},
            "deadline": d(60), "applyLink": "https://www.jntataendowment.org",
            "documents": ["UG marksheet (60%+)", "Abroad admission letter", "Aadhaar", "References"],
            "tags": ["tata", "abroad", "loan scholarship", "masters"],
        },
        {
            "source_id": "hdfc_badhte_kadam",
            "name": "HDFC Bank Badhte Kadam Scholarship",
            "source": "HDFC Bank Parivartan",
            "amount": 30000,
            "description": "For Class 11-12 and UG students from economically weaker families.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 300000, "minPercentage": 55, "educationLevels": ["11th", "12th", "ug"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://www.buddy4study.com/scholarship/hdfc-bank-badhte-kadam-scholarship",
            "documents": ["Income certificate", "Marksheet (55%+)", "Aadhaar", "College/school ID"],
            "tags": ["hdfc", "school", "ug", "financial need"],
        },
    ]


# ── 9. SECTOR-SPECIFIC (Engineering, Medical, Law) ──────

def get_sector_specific() -> List[Dict]:
    return [
        {
            "source_id": "gate_scholarship_pg",
            "name": "GATE Scholarship for M.Tech/M.E Students",
            "source": "MHRD - Government of India",
            "amount": 156000,
            "description": "Scholarship of ₹12,400/month for GATE qualified students pursuing M.Tech/M.E at recognized institutes.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 0, "educationLevels": ["pg"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://gate.iisc.ac.in",
            "documents": ["GATE scorecard", "M.Tech admission proof", "Aadhaar", "Bank passbook"],
            "tags": ["gate", "mtech", "engineering", "pg", "research"],
        },
        {
            "source_id": "pm_research_fellowship",
            "name": "Prime Minister's Research Fellowship (PMRF)",
            "source": "Ministry of Education",
            "amount": 840000,
            "description": "For direct PhD at IITs/IISc. ₹70,000-80,000/month stipend + ₹2 lakh research grant per year.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 80, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(120), "applyLink": "https://www.pmrf.in",
            "documents": ["B.Tech/M.Sc marksheet (80%+)", "GATE/NET scorecard", "Research proposal", "Aadhaar"],
            "tags": ["pmrf", "phd", "iit", "iisc", "research", "fellowship"],
        },
        {
            "source_id": "icar_jrf",
            "name": "ICAR-JRF Agriculture Research Fellowship",
            "source": "ICAR",
            "amount": 372000,
            "description": "For students pursuing PhD in agriculture through ICAR entrance exam.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["phd"], "gender": "all"},
            "deadline": d(140), "applyLink": "https://icar.org.in",
            "documents": ["ICAR JRF scorecard", "B.Sc/M.Sc (Agriculture) marksheet", "Aadhaar"],
            "tags": ["agriculture", "icar", "jrf", "phd", "research"],
        },
        {
            "source_id": "medical_nhs_scholarship",
            "name": "National Health Science Scholarship",
            "source": "Ministry of Health",
            "amount": 100000,
            "description": "For meritorious MBBS students from SC/ST/OBC families at top medical colleges.",
            "eligibility": {"categories": ["sc", "st", "obc"], "states": ["all"], "maxIncome": 450000, "minPercentage": 0, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(100), "applyLink": "https://scholarships.gov.in",
            "documents": ["Caste certificate", "NEET scorecard", "MBBS admission proof", "Income certificate", "Aadhaar"],
            "tags": ["medical", "mbbs", "sc", "st", "obc", "neet"],
        },
        {
            "source_id": "bar_council_scholarship",
            "name": "Bar Council of India Law Scholarship",
            "source": "Bar Council of India",
            "amount": 36000,
            "description": "For economically weaker law students pursuing LLB at BCI recognized law colleges.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 300000, "minPercentage": 55, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://www.barcouncilofindia.org",
            "documents": ["Income certificate", "LLB admission proof", "Marksheet (55%+)", "Aadhaar"],
            "tags": ["law", "llb", "bar council", "legal"],
        },
        {
            "source_id": "fashion_design_scholarship",
            "name": "NIFT Merit Scholarship",
            "source": "NIFT - Ministry of Textiles",
            "amount": 40000,
            "description": "For meritorious students admitted to NIFT programs through NIFT entrance examination.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 450000, "minPercentage": 0, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://www.nift.ac.in",
            "documents": ["NIFT admission letter", "Income certificate", "Aadhaar", "Class XII marksheet"],
            "tags": ["nift", "fashion", "design", "textiles"],
        },
        {
            "source_id": "ca_foundation_scholarship",
            "name": "ICAI Merit Scholarship for CA Students",
            "source": "ICAI - Institute of Chartered Accountants",
            "amount": 24000,
            "description": "For CA Foundation/Intermediate students from economically backward families.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 200000, "minPercentage": 55, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://www.icai.org",
            "documents": ["Income certificate", "CA enrollment proof", "Class XII marksheet", "Aadhaar"],
            "tags": ["ca", "icai", "commerce", "chartered accountant"],
        },
        {
            "source_id": "icsi_scholarship",
            "name": "ICSI Scholarship for Company Secretary Students",
            "source": "ICSI - Institute of Company Secretaries",
            "amount": 18000,
            "description": "For SC/ST/Physically Challenged CS Foundation/Executive students from ICSI.",
            "eligibility": {"categories": ["sc", "st"], "states": ["all"], "maxIncome": 0, "minPercentage": 50, "educationLevels": ["ug"], "gender": "all"},
            "deadline": d(110), "applyLink": "https://www.icsi.edu",
            "documents": ["Caste certificate", "ICSI enrollment proof", "Marksheet", "Aadhaar"],
            "tags": ["cs", "icsi", "company secretary", "commerce"],
        },
    ]


# ── 10. SPORTS, CULTURAL & SPECIAL ──────────────────────

def get_special_category() -> List[Dict]:
    return [
        {
            "source_id": "sports_scholarship_sai",
            "name": "SAI National Sports Scholarship",
            "source": "Sports Authority of India (SAI)",
            "amount": 36000,
            "description": "For outstanding sportspersons at national/international level pursuing education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 0, "educationLevels": ["ug", "pg", "11th", "12th"], "gender": "all"},
            "deadline": d(80), "applyLink": "https://sportsauthorityofindia.nic.in",
            "documents": ["National/international sports certificate", "Aadhaar", "Marksheet", "Admission proof"],
            "tags": ["sports", "sai", "athlete", "national"],
        },
        {
            "source_id": "central_sector_sports",
            "name": "National Welfare Fund for Sportspersons",
            "source": "Ministry of Youth Affairs and Sports",
            "amount": 500000,
            "description": "One-time financial assistance to outstanding medal-winning sportspersons in penury.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["all"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://yas.nic.in",
            "documents": ["Sports achievement certificate (national/international medal)", "Income certificate", "Aadhaar"],
            "tags": ["sports", "medal", "national welfare"],
        },
        {
            "source_id": "pm_scholarship_exservicemen",
            "name": "PM Scholarship Scheme for Ex-Servicemen/Ex-Coast Guard",
            "source": "KSB - Ministry of Defence",
            "amount": 30000,
            "description": "For wards/widows of ex-servicemen and ex-coast guard pursuing professional UG/PG courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://ksb.gov.in",
            "documents": ["Ex-serviceman PPO/discharge certificate", "Marksheet (60%+)", "Aadhaar", "Admission proof"],
            "tags": ["ex-servicemen", "defence", "ksb", "pm scholarship"],
        },
        {
            "source_id": "pm_scholarship_rpf",
            "name": "PM Scholarship for RPF/RPSF Personnel Wards",
            "source": "Ministry of Railways",
            "amount": 30000,
            "description": "For wards of RPF/RPSF personnel killed or disabled in action pursuing professional courses.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 0, "minPercentage": 60, "educationLevels": ["ug", "pg"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://scholarships.gov.in",
            "documents": ["RPF personnel certificate", "Marksheet (60%+)", "Aadhaar", "Admission proof"],
            "tags": ["rpf", "railways", "defence", "pm scholarship"],
        },
        {
            "source_id": "special_nc_obc_scholarship",
            "name": "NC-OBC Scholarship Scheme",
            "source": "NSP - Ministry of Social Justice",
            "amount": 15000,
            "description": "For Non-Creamy Layer OBC students pursuing studies at post-matric level.",
            "eligibility": {"categories": ["obc"], "states": ["all"], "maxIncome": 800000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(115), "applyLink": "https://scholarships.gov.in",
            "documents": ["NCL-OBC certificate", "Aadhaar", "Marksheet", "Income certificate"],
            "tags": ["obc", "ncl", "non-creamy layer", "nsp"],
        },
        {
            "source_id": "transgender_scholarship",
            "name": "Scholarship for Transgender Students",
            "source": "NSP - Ministry of Social Justice",
            "amount": 13500,
            "description": "For transgender students pursuing post-matric education to support their academic journey.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 250000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(115), "applyLink": "https://scholarships.gov.in",
            "documents": ["Transgender certificate", "Income certificate", "Aadhaar", "Marksheet"],
            "tags": ["transgender", "nsp", "social justice"],
        },
        {
            "source_id": "de_notified_tribes",
            "name": "Dr. Ambedkar Post Matric Scholarship for De-Notified Tribes",
            "source": "NSP - Ministry of Social Justice",
            "amount": 15000,
            "description": "For students from De-Notified, Nomadic and Semi-Nomadic Tribes pursuing post-matric education.",
            "eligibility": {"categories": ["sc", "st"], "states": ["all"], "maxIncome": 200000, "minPercentage": 0, "educationLevels": ["11th", "12th", "ug", "pg"], "gender": "all"},
            "deadline": d(115), "applyLink": "https://scholarships.gov.in",
            "documents": ["DNT/SNT certificate", "Income certificate", "Aadhaar", "Marksheet"],
            "tags": ["dnt", "nomadic", "tribal", "nsp"],
        },
        {
            "source_id": "weavers_scholarship",
            "name": "Sant Kabir Scholarship for Weavers",
            "source": "Ministry of Textiles",
            "amount": 12000,
            "description": "For children of handloom weavers pursuing school and higher education.",
            "eligibility": {"categories": ["all"], "states": ["all"], "maxIncome": 200000, "minPercentage": 50, "educationLevels": ["9th", "10th", "11th", "12th", "ug"], "gender": "all"},
            "deadline": d(90), "applyLink": "https://handlooms.nic.in",
            "documents": ["Weaver parent certificate", "Income certificate", "Marksheet", "Aadhaar"],
            "tags": ["weavers", "handloom", "textiles", "artisan"],
        },
    ]


# ── MASTER FUNCTION ──────────────────────────────────────

def run_all_scrapers(db) -> int:
    print("\nStarting ScholarZone scraper pipeline...\n")
    all_scholarships = []

    groups = [
        ("Central Government (NSP)", get_central_govt),
        ("AICTE & UGC", get_aicte_ugc),
        ("DST & INSPIRE", get_dst_inspire),
        ("CBSE & NTA", get_cbse_nta),
        ("State - South India", get_state_south),
        ("State - North & West India", get_state_north_west),
        ("State - East India", get_state_east),
        ("Private & Corporate", get_private_corporate),
        ("Sector Specific", get_sector_specific),
        ("Special Categories", get_special_category),
    ]

    for name, fn in groups:
        try:
            results = fn()
            all_scholarships.extend(results)
            print(f"  {name}: {len(results)} scholarships")
        except Exception as e:
            print(f"  ERROR in {name}: {e}")

    print(f"\nTotal collected: {len(all_scholarships)} scholarships")

    if db is not None:
        print("Saving to Firestore...")
        count = to_firestore(db, all_scholarships)
        print(f"Saved {count} scholarships to Firestore!")
        return count
    else:
        return len(all_scholarships)


if __name__ == "__main__":
    total = run_all_scrapers(None)
    print(f"\nGrand Total: {total} scholarships")